id: P010603
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18787
  title: བཅའ་ཁྲིམས་རོགས་སྐྱོར་ཐད་ཀྱི་ཉེར་མཁོའི་ཁྲིད་སྟོན་དཔེ་དེབ།
  author: ''
  volumes:
    5340096365684795969665cff7f3c2d1:
      image_group_id: I8LS18789
      title: ''
      volume_number: 1
      total_pages: 266
